version: '2'

services:
  app:
    build: .
    ports:
      - "8000:8000"
      - "5858:5858"
    volumes:
      - ./src:/user/development/image-gallery-app/src
    depends_on:
      - mongo
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
